### ISSUE TITLE
Excellent code !

### ISSUE THREAD

**Issue by kelexel** [psy0rz/ledanim#1]
Runs very well on an ESP12

Out of curiosity, have you made other animation scripts publicly available ? ;)

Best regards

**Comment by psy0rz** [comment]
what do you mean? all the animations for ledanim are available in the webinterface.

if someone creates new animations for ledanim, please send a pull request.:)

**Comment by kelexel** [comment]
Well, yes, I was wondering if you, or someone else, had created other animations that the ones already present in the web UI ;)
Nevertheless, great work!

**Comment by psy0rz** [comment]
i was plannng to create many more animations,  but had no time yet. Also maybe ill intergrate the animationpart into espeasy and leave the webinterface external. (still have to find out how feasable that is)

Edwin

**Comment by kelexel** [comment]
Well, running a ui on a different host (even locally) is pretty easy..
I mean, there are many easy ways to get a SAP running in no time nowadays..
The trick is only to create a proper settings structure, and upload it (as JSON ?) to the remote ESPs..
Than the ESPs only need to be able to receive the POST data, decode is as JSON (preferably validating it's content aswell ;) and store the new JSON "settings" as a new preset ?
I'ld be glad to help on the UI if you want.. (using React, or Polymer for instance...)

**Comment by psy0rz** [comment]
i already solved that the webinterface is hosted external (on github actually).

if you update your version, and also upload the new spiffs data, then your esp will automaticly redirect you to git hub, with your esp8266 adress as GET parameter.

Edwin
