### ISSUE TITLE
hi, very interesting project

### ISSUE THREAD

**Issue by macmattes** [psy0rz/ledanim#2]
great project, in this combination.
do you think it will be possible to store more then one configured sets on the esp flash to select them without the server or web stuff, or to build a standalone lighting device?

i copied the web stuff to my local server and also changed the links in the code accordingly.
works fine. is it possible to control the functions with node-red and how?

**Comment by psy0rz** [comment]
It probably is, i dont have time to look into it now. Depends on what you want to control: The simplest way would be to just copy/paste the request that the webapp sends to your ESP.
